//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUMGAhorcado
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public class AHORCADOEntities : DbContext
    {
        public AHORCADOEntities()
            : base("name=AHORCADOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_DIFICULTAD> TBL_DIFICULTAD { get; set; }
        public virtual DbSet<TBL_PALABRA> TBL_PALABRA { get; set; }
    }
}
