//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUMGAhorcado
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PALABRA
    {
        public int IDPALABRA { get; set; }
        public string PALABRA { get; set; }
        public Nullable<int> DIFICULTAD { get; set; }
    
        public virtual TBL_DIFICULTAD TBL_DIFICULTAD { get; set; }
    }
}
